### PR TITLE
Fix: English title display is incomplete

### PR DESCRIPTION
**Pull request by jerryc127**
### Description

image

image

### CODE REVIEW

**Comment by Innei** [comment]
@jerryc127 Nice work, but the title and the following question are too loose

CleanShot 2024-09-24 at 10  07 37@2x

**Comment by jerryc127** [comment]
> @jerryc127 Nice work, but the title and the following question are too loose
> 
> CleanShot 2024-09-24 at 10  07 37@2x

I change line-height: 1.25 to line-height: 1.15, it will be better

**Comment by Innei** [comment]
I think it's still too loose here.

**Comment by jerryc127** [comment]
image

我認爲已經是很好了，字母 g 已經很接近 ‘項目’兩個字了

**Pull request merged**
