### PR TITLE
feat(i18n): add ar-iq/kw/tn language support

### PR DESCRIPTION
**Pull request by upupnoah**
Added ar-iq/kw/tn translations to the application, including localization for app content, common phrases, external resources, language settings, and shortcuts.

### CODE REVIEW

**Comment by upupnoah** [comment]
Local testing has been completed, and the language can be switched normally.

**Comment by Innei** [comment]
Resolve the conflicts plz, thx @upupnoah

**Comment by jerryc127** [comment]
you need to change the fileName to xx-AA format
image

**Comment by upupnoah** [comment]
> you need to change the fileName to xx-AA format image

Git does not differentiate between file name case by default. I'll clear the cache and commit again.

**Review by Innei — APPROVED** [review]
Nice

**Comment by jerryc127** [comment]
Some file still not change filename

**Comment by upupnoah** [comment]
> Some file still not change filename

It has already been changed, but it cannot be seen in the git changes because it is case-insensitive. This commit has already been merged into the dev branch, and you can check the situation in the dev branch.

**Comment by jerryc127** [comment]
> > Some file still not change filename
> 
> 
> 
> It has already been changed, but it cannot be seen in the git changes because it is case-insensitive. This commit has already been merged into the dev branch, and you can check the situation in the dev branch.

image

**Comment by upupnoah** [comment]
> > > Some file still not change filename
> > 
> > 
> > It has already been changed, but it cannot be seen in the git changes because it is case-insensitive. This commit has already been merged into the dev branch, and you can check the situation in the dev branch.
> 
> image

image
The web version is fine.

**Pull request merged**
