### PR TITLE
fix: style

### LINKED ISSUE #334: Scrollbar flashes when previewing large images

### PR DESCRIPTION
**Pull request by Soya-xy**
### Linked Issues

Fixes #334

### CODE REVIEW

**Comment by hyoban** [comment]
Can you provide screenshots reflecting the changes before and after the modification? Thanks!

**Comment by Soya-xy** [comment]
Well, it's my fault

[0f6d946](https://github.com/RSSNext/Follow/pull/359/commits/0f6d946320a7294078db090661827e6ca681f9c3) 
Before:
QQ_1726109868967

After:
QQ_1726109507432
---
[c5d94e7](https://github.com/RSSNext/Follow/pull/359/commits/c5d94e7bad7cc47b984ba223960d92858927e73c)
Before:
QQ_1726109888429

After:
image

**Comment by hyoban** [comment]
Does this also fixes #334?

**Comment by Soya-xy** [comment]
I think so，
--- 
Before:

https://github.com/user-attachments/assets/3d43c2fe-c4be-4a11-b5e1-02fbce8b36b7


After:

https://github.com/user-attachments/assets/961f8a9b-1f2d-4f07-be7b-8d88a0cc5675

**Review by hyoban — APPROVED** [review]

**Comment by hyoban** [comment]
Thanks for your contribution!

**Pull request merged**
