### PR TITLE
feat: add copy title to context menu of feed entry

### LINKED ISSUE #745: Provides a way to copy the feed title.
### Clear and concise description of the problem

There is currently no way to copy the title of the feed.

### Suggested solution

Would like to add an option to the title's right-click menu for copying the title.

image

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by cesaryuan**
### Description

Add copy title to context menu of feed entry

image

### Linked Issues

Close #745

### CODE REVIEW

**Comment by hyoban** [comment]
Just right-click on the title and you should be able to copy it.

ScreenShot 2024-10-08 16 49 50

**Comment by cesaryuan** [comment]
> Just right-click on the title and you should be able to copy it.
> 
> ScreenShot 2024-10-08 16 49 50

On windows electron, the title can not be selected. I recorded a video to show this.


https://github.com/user-attachments/assets/f6abc1b1-098f-45ad-a890-24bc916bf6e9

**Comment by hyoban** [comment]
It's weird. Can you just click on it? You don't have to select the text.

**Comment by cesaryuan** [comment]
> It's weird. Can you just click on it? You don't have to select the text.

Clicking the title will open link in browser, instead of selecting the title text.

**Comment by hyoban** [comment]
Sorry, i mean right click.

**Comment by cesaryuan** [comment]
> Sorry, i mean right click.

Right clicking just open the context menu. 

https://github.com/user-attachments/assets/2ce04eac-6d24-4599-957f-4263f174085b

**Comment by cesaryuan** [comment]
> image
> 使用这个图标来复制标题似乎不太合适。
> It seems inappropriate to use this icon to copy the title.


确实，我没注意到修改上下文菜单这里也会出现

**Comment by Innei** [comment]
Now electron can copy the title in the context menu, so I've hidden the toolbar icon.

**Pull request merged**
