### PR TITLE
feat: muti select action

### PR DESCRIPTION
**Pull request by hyoban**
### Description

https://github.com/user-attachments/assets/b686ed38-4870-4e52-947d-00714e500eca

https://github.com/user-attachments/assets/e9c3000b-0c46-4ae7-99ac-87142eae78ad

### Additional context

- Related server-side commits https://github.com/RSSNext/follow-server/commit/3179b5c5784a3d074405dbad141da38ddb30d9e5

### CODE REVIEW

**Comment by Innei** [comment]
@hyoban try react-selecto ?

**Comment by hyoban** [comment]
Will take a look

**Review by Innei — APPROVED** [review]
Nice implement, are there any plans to implement DnD?

**Comment by hyoban** [comment]
Of course, maybe complete it in a new PR later

**Comment by Innei** [comment]
A UI optimization point: change the selection color to accent color, with a transparency of about 60-70 ?

**Comment by Innei** [comment]
Another UX key: need to support Shift Or Ctrl/Cmd multi-selection

Also need to pay attention to the scope of the shortcut keys. #789 @lawvs will probably support this refactor afterward.

**Comment by hyoban** [comment]
multi-selection by cmd is already supported

https://github.com/user-attachments/assets/40eb4d4a-c8ff-4417-b32d-dfc098072a08

**Pull request merged**
