### PR TITLE
I18n/add  ar-iq/ar-kw/ar-tn

### PR DESCRIPTION
**Pull request by upupnoah**

### CODE REVIEW

**Comment by jerryc127** [comment]
After your modification, have you tried running 'pnpm run dev:web', then selecting the corresponding language to see if it has taken effect?

**Comment by upupnoah** [comment]
> After your modification, have you tried running 'pnpm run dev:web', then selecting the corresponding language to see if it has taken effect?
I cannot switch the language in the local testing environment because I can't log in; the language switching settings should be displayed after logging in.

image

**Comment by upupnoah** [comment]
> After your modification, have you tried running 'pnpm run dev:web', then selecting the corresponding language to see if it has taken effect?

This PR has some issues, I will resubmit it and have modified many unnecessary files.

**Comment by upupnoah** [comment]
> > > After your modification, have you tried running 'pnpm run dev:web', then selecting the corresponding language to see if it has taken effect?
> > > I cannot switch the language in the local testing environment because I can't log in; the language switching settings should be displayed after logging in.
> > 
> > 
> > image
> 
> https://app.follow.is/__debug_proxy
> 
> use this to test, you need to login in https://app.follow.is/


Thanks, I'll try it.

**Pull request closed without merging**
