### PR TITLE
fix: optimize about share btn padding

### PR DESCRIPTION
**Pull request by winchesHe**
### Description

Before

https://github.com/user-attachments/assets/84908402-5ef3-464d-8e32-d66f7f2f59d0

After

https://github.com/user-attachments/assets/04258300-2ffa-4acd-9150-a604025b9c83

### CODE REVIEW

**Comment by hyoban** [comment]
Thank you very much, but I think the current situation is okay

**Comment by Innei** [comment]
@hyoban This fix is correct, it affects accessibility.

**Comment by hyoban** [comment]
Sorry for my mistake, thanks for your contribution

**Comment by winchesHe** [comment]
@Innei @hyoban 🫰

**Pull request merged**
