### PR TITLE
feat: support preview feed view

### PR DESCRIPTION
**Pull request by lawvs**
Fix https://github.com/RSSNext/Follow/issues/430. This pull request introduces a new feature that allows users to preview feed views before following. 

https://github.com/user-attachments/assets/092f8453-5f79-46d9-a4a6-a9b41bd1153c

### CODE REVIEW

**Comment by Innei** [comment]
Very good idea.

But the default expanding preview doesn't look good on it, which takes up a very large area.

**Comment by lawvs** [comment]
> But the default expanding preview doesn't look good on it, which takes up a very large area.

Don't worry, we have several methods to alleviate this issue, such as placing it at the bottom or adding a collapse button for the preview item.


The following is my preferred solution， place the preview card on the bottom

image

**Comment by hyoban** [comment]
We may need to create a simplified version of the component to preview feeds that have not yet been stored in the database. Now `EntryItem` needs to have `entry.id`.

**Comment by lawvs** [comment]
We are currently waiting for @hyoban's new preview component, so this pull request is pending.

**Pull request closed without merging**
