### PR TITLE
fix: feeds not centered on lists share page

### PR DESCRIPTION
**Pull request by DFobain**
### PR Type

- [ ] Feature
- [ ] Bugfix
- [ ] Hotfix
- [ ] Other (please describe):

### Changelog

- [ ] I have updated the changelog/next.md with my changes.

### CODE REVIEW

**Review by Innei — COMMENTED** [review]
Are you wanting to change it to this?

image

**Comment by DFobain** [comment]
> Are you wanting to change it to this?
> image

yea, some say it should be centered. If it doesn't fit, the pr can be closed.

**Comment by ericyzhu** [comment]
> Are you wanting to change it to this?
> 
> image

So ugly...

**Comment by Innei** [comment]
No, this does not conform to the design principles, and it is not even aligned on both sides.

**Pull request closed without merging**
