### PR TITLE
fix: proxy img.hellogithub.com

### PR DESCRIPTION
**Pull request by Miroxyz**

### CODE REVIEW

**Comment by hyoban** [comment]
Can you provide a feed that needs this?

**Comment by Miroxyz** [comment]
rsshub://hellogithub/month

**Comment by Miroxyz** [comment]
Perhaps the software can provide a configuration to configure these custom headers.

**Comment by hyoban** [comment]
Works for me already

ScreenShot 2024-09-29 10 52 47

**Comment by Miroxyz** [comment]
image
image

**Comment by hyoban** [comment]
We are doing an AB Test for the new image proxy service, maybe you are not in it. You should be able to browse images normally after the full release. Thanks for your contribution, but I'm closing this PR.

**Pull request closed without merging**
