### PR TITLE
Add zh-tw (台灣繁體中文）

### PR DESCRIPTION
**Pull request by jerryc127**
### Description

Add zh-tw (台灣繁體中文）

### Additional context

How can I test language files locally? When I run pnpm run dev:web or pnpm run dev, the software requires login to change settings, but I can't log in locally (using GitHub).

### CODE REVIEW

**Comment by Innei** [comment]
https://github.com/RSSNext/Follow#contributing

**Comment by jerryc127** [comment]
> Hi, please checkout readme https://github.com/RSSNext/Follow#contributing

I followed the Contributing guide, and I encountered a login issue. The redirection to GitHub doesn't allow me to log in.

**Comment by TonyRL** [comment]
#398

**Comment by jerryc127** [comment]
我遇到了一個問題，我使用 npm run generator:i18n-template 創建語言文檔，它幫我生產了很多 zh-tw 的 json, 我更改了語言文件，並本地測試，運行 pnpm run dev:web ，但是更改語言為 繁體中文，并沒有生效。我試著把 follow 自動生成的 所有 zh-tw 文件改成 zh-TW, 並修改相應的 js, 運行后，語言文件生效了。那問題出在哪裏？我應該把所有默認生成的  zh-tw 文件改成 zh-TW 麽

--- 

I encountered a problem where I used npm run generator:i18n-template to create language files, which generated many zh-tw JSON files. After modifying the language files and testing locally by running pnpm run dev:web, the changes for Traditional Chinese were not applied. I tried renaming all the auto-generated zh-tw files to zh-TW and modifying the corresponding JS files, and the language files worked. What could be the issue? Should I rename all the default-generated zh-tw files to zh-TW?

@Innei

**Comment by Innei** [comment]
Yes， this is a bug, you should rename json file as lower-upper

**Comment by jerryc127** [comment]
> Yes， this is a bug, you should rename json file as lower-upper

OK, Done
image

**Comment by Innei** [comment]
Please resolves conflicts

**Comment by jerryc127** [comment]
> Please resolves conflicts

done !

**Review by Innei — APPROVED** [review]

**Pull request merged**
