### PR TITLE
chore(i18n): improve zh-CN.json

### PR DESCRIPTION
**Pull request by hexWars**
### Description

I believe the current translation isn't quite suitable, not aesthetically pleasing, so I made some slight adjustments.
image

### PR Type

- [ ] Feature
- [ ] Bugfix
- [ ] Hotfix
- [X] Other (please describe): i18n

### Changelog

- [ ] I have updated the changelog/next.md with my changes.

### CODE REVIEW

**Comment by ericyzhu** [comment]
The principle of localization is to change untranslated English nouns from plural to singular, as Chinese does not have the concept of plural.  This cannot be translated based on personal preference.

**Comment by hexWars** [comment]
> In typical localization guidelines, untranslated English nouns will be changed from plural to singular form, as there is no concept of plurality in the Chinese context.
> 
> Translation cannot be done based on personal preferences.

I reviewed the Traditional Chinese translation and noticed that it includes 's' and uses an asterisk with the period, which doesn't look aesthetically pleasing.

If you believe this is unnecessary, feel free to close the PR.

**Comment by hexWars** [comment]
image

**Comment by hexWars** [comment]
Okay, I respect your suggestion. I am about to close the PR.

**Pull request closed without merging**
