### PR TITLE
feat: add support for pointer cursor

### PR DESCRIPTION
**Pull request by yuzhang9804**
### Description
- Add support for cursor pointer

image

### CODE REVIEW

**Comment by Innei** [comment]
Even though I don't have this option turned on, the pointer to Switch is cursor.

**Comment by yuzhang9804** [comment]
- The dependencies for useEffect haven't been added. 
- The cursor now has multiple CSS variables. Should this be adjusted? If there's no need for atomization, I feel one CSS variable might suffice.

**Comment by jerryc127** [comment]
這種不是應該强制開啓的麽，不需要提供設置。
follow 現在很多可交互的item, 即沒有Hover 效果，也沒有 pointer cursor
很難察覺這是可以點擊的

---

This should be enabled by default and shouldn't require configuration. There are many interactive items in Follow, but they lack both hover effects and a pointer cursor, making it hard to tell that they are clickable.

**Comment by yuzhang9804** [comment]
I've sent a direct message to Innei about this. The default cursor being set to 'default' is intended to make the application feel more like a native app.

**Comment by Innei** [comment]
https://github.com/RSSNext/Follow/issues/442

**Comment by yuzhang9804** [comment]
If there are plans to address this issue, should I close this PR for now?

**Pull request merged**
