### PR TITLE
fix: cmdk panel layout

### PR DESCRIPTION
**Pull request by Debbl**
### Description
fix `cmdk` panel footer layout.

image

fixed the `ScrollArea` area and changed some spacing.

image

result

image

### CODE REVIEW

**Comment by Innei** [comment]
I can't reproduce.

This is the current UI and there is no problem.
CleanShot 2024-10-10 at 3  16 02@2x

**Comment by Debbl** [comment]
> I can't reproduce.
> 
> This is the current UI and there is no problem. CleanShot 2024-10-10 at 3  16 02@2x

Try scrolling the search results across the footer.

image

**Comment by Innei** [comment]
CleanShot 2024-10-10 at 3  41 41@2x

**Comment by Debbl** [comment]
@Innei this is my Chrome version `129.0.6668.101`，If there is still a problem with the same version, it should be a problem with my device, I haven't tested it on other devices.

image

db1d19076c781696b9421f53dd79c35a6f49a324
image

**Review by Innei — APPROVED** [review]

**Pull request merged**
